const items2 = [
  { ID: 1, name: "Acne" },
  { ID: 2, name: "Allergies" },
  { ID: 3, name: "Alzheimer's disease" },
  { ID: 4, name: "Anemia" },
  { ID: 5, name: "Anxiety disorders" },
  { ID: 6, name: "Arthritis" },
  { ID: 7, name: "Asthma" },
  { ID: 8, name: "Atherosclerosis" },
  { ID: 9, name: "Autism" },
  { ID: 10, name: "Bipolar disorder" },
  { ID: 11, name: "Bronchitis" },
  { ID: 12, name: "Cancer" },
  { ID: 13, name: "Cataracts" },
  { ID: 14, name: "Celiac disease" },
  { ID: 15, name: "Chlamydia" },
  { ID: 16, name: "Chronic obstructive pulmonary disease (COPD)" },
  { ID: 17, name: "Cirrhosis" },
  { ID: 18, name: "Colitis" },
  { ID: 19, name: "Common cold" },
  { ID: 20, name: "Conjunctivitis" },
  { ID: 21, name: "Coronary heart disease" },
  { ID: 22, name: "Crohn's disease" },
  { ID: 23, name: "Dementia" },
  { ID: 24, name: "Depression" },
  { ID: 25, name: "Diabetes" },
  { ID: 26, name: "Diarrhea" },
  { ID: 27, name: "Down syndrome" },
  { ID: 28, name: "Dyslexia" },
  { ID: 29, name: "Eczema" },
  { ID: 30, name: "Epilepsy" },
  { ID: 31, name: "Erectile dysfunction" },
  { ID: 32, name: "Fibromyalgia" },
  { ID: 33, name: "Gastritis" },
  { ID: 34, name: "Gastroenteritis" },
  { ID: 35, name: "Glaucoma" },
  { ID: 36, name: "Gonorrhea" },
  { ID: 37, name: "Gout" },
  { ID: 38, name: "Graves' disease" },
  { ID: 39, name: "Hemorrhoids" },
  { ID: 40, name: "Hepatitis" },
  { ID: 41, name: "Herpes" },
  { ID: 42, name: "High blood pressure (hypertension)" },
  { ID: 43, name: "HIV/AIDS" },
  { ID: 44, name: "Hyperthyroidism" },
  { ID: 45, name: "Hypothyroidism" },
  { ID: 46, name: "Influenza" },
  { ID: 47, name: "Insomnia" },
  { ID: 48, name: "Irritable bowel syndrome (IBS)" },
  { ID: 49, name: "Jaundice" },
  { ID: 50, name: "Kidney disease" },
  { ID: 51, name: "Leukemia" },
  { ID: 52, name: "Lupus" },
  { ID: 53, name: "Lyme disease" },
  { ID: 54, name: "Malaria" },
  { ID: 55, name: "Measles" },
  { ID: 56, name: "Meningitis" },
  { ID: 57, name: "Migraines" },
  { ID: 58, name: "Mononucleosis" },
  { ID: 59, name: "Multiple sclerosis (MS)" },
  { ID: 60, name: "Mumps" },
  { ID: 61, name: "Narcolepsy" },
  { ID: 62, name: "Obesity" },
  { ID: 63, name: "Obsessive-compulsive disorder (OCD)" },
  { ID: 64, name: "Osteoarthritis" },
  { ID: 65, name: "Osteoporosis" },
  { ID: 66, name: "Otitis media" },
  { ID: 67, name: "Ovarian cancer" },
  { ID: 68, name: "Pancreatitis" },
  { ID: 69, name: "Parkinson's disease" },
  { ID: 70, name: "Peptic ulcer" },
  { ID: 71, name: "Phobias" },
  { ID: 72, name: "Pneumonia" },
  { ID: 73, name: "Polio" },
  { ID: 74, name: "Post-traumatic stress disorder (PTSD)" },
  { ID: 75, name: "Pregnancy complications" },
  { ID: 76, name: "Prostate cancer" },
  { ID: 77, name: "Psoriasis" },
  { ID: 78, name: "Rabies" },
  { ID: 79, name: "Rheumatoid arthritis" },
  { ID: 80, name: "Ringworm" },
  { ID: 81, name: "Rotavirus" },
  { ID: 82, name: "Salmonella infection" },
  { ID: 83, name: "Sarcoidosis" },
  { ID: 84, name: "SARS-CoV-2 (COVID-19)" },
  { ID: 85, name: "Schizophrenia" },
  { ID: 86, name: "Scoliosis" },
  { ID: 87, name: "Seasonal affective disorder (SAD)" },
  { ID: 88, name: "Sexually transmitted diseases (STDs)" },
  { ID: 89, name: "Shingles" },
  { ID: 90, name: "Ulcerative colitis" },
  { ID: 91, name: "Sickle cell anemia" },
  { ID: 92, name: "Sinusitis" },
  { ID: 93, name: "Sleep apnea" },
  { ID: 94, name: "Smallpox" },
  { ID: 95, name: "Stroke" },
  { ID: 96, name: "Strep throat" },
  { ID: 97, name: "Tetanus" },
  { ID: 98, name: "Thyroid disorders" },
  { ID: 99, name: "Tourette's syndrome" },
  { ID: 100, name: "Tuberculosis (TB)" },
];

export default items2;
